In [1]:
import torch

# reshapping,stacking,squeezing and unsqueezing tensors

##  lets see the definition of them all know
    * reshaping:-reshapes an input tensor
    *view:-returns a view of a tensor of a certain shape but keep the same memory
    *stacking:-combines a stack of tensors on top of each other whether vertical or horizontal
    *squeez:- removes all 1 dimension from a tensor
    *unsqueez:add a 1 dimension to a tensor

In [2]:
tensor=torch.arange(1,11)
print(tensor.shape)
print(tensor)

torch.Size([10])
tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])


In [3]:
print(tensor.reshape([5,2]))

tensor([[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10]])


In [4]:
print(tensor)

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])


In [5]:
print(tensor.reshape([10,1]))

tensor([[ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10]])


In [6]:
# using view to change the shape of the tensor array
x=torch.arange(1,11)
z=x.view(1,10)
print(x)
print(z)

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])
tensor([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])


In [7]:
x[0]=90
print(x)
print(z)

tensor([90,  2,  3,  4,  5,  6,  7,  8,  9, 10])
tensor([[90,  2,  3,  4,  5,  6,  7,  8,  9, 10]])


In [8]:
#lets use stack to change some stuff
torch.stack([x,x,x,x],dim=0)

tensor([[90,  2,  3,  4,  5,  6,  7,  8,  9, 10],
        [90,  2,  3,  4,  5,  6,  7,  8,  9, 10],
        [90,  2,  3,  4,  5,  6,  7,  8,  9, 10],
        [90,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [9]:
#know lets try along the first dimension which is the vertical one
torch.stack([x,x,x,x,x],dim=1)

tensor([[90, 90, 90, 90, 90],
        [ 2,  2,  2,  2,  2],
        [ 3,  3,  3,  3,  3],
        [ 4,  4,  4,  4,  4],
        [ 5,  5,  5,  5,  5],
        [ 6,  6,  6,  6,  6],
        [ 7,  7,  7,  7,  7],
        [ 8,  8,  8,  8,  8],
        [ 9,  9,  9,  9,  9],
        [10, 10, 10, 10, 10]])

In [10]:
#lets try squeez 
a=torch.zeros(2,1,2,1,1)
print(a)
af=torch.squeeze(a)
print(af)

tensor([[[[[0.]],

          [[0.]]]],



        [[[[0.]],

          [[0.]]]]])
tensor([[0., 0.],
        [0., 0.]])


In [11]:
#another example of squuez
a=torch.zeros(2,3,1,2,1)
print(a)
af=torch.squeeze(a)
print(af)

tensor([[[[[0.],
           [0.]]],


         [[[0.],
           [0.]]],


         [[[0.],
           [0.]]]],



        [[[[0.],
           [0.]]],


         [[[0.],
           [0.]]],


         [[[0.],
           [0.]]]]])
tensor([[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]])


In [12]:
a=torch.ones(2,1,2,3,1)
print(a)
af=torch.squeeze(a)
print(a)

tensor([[[[[1.],
           [1.],
           [1.]],

          [[1.],
           [1.],
           [1.]]]],



        [[[[1.],
           [1.],
           [1.]],

          [[1.],
           [1.],
           [1.]]]]])
tensor([[[[[1.],
           [1.],
           [1.]],

          [[1.],
           [1.],
           [1.]]]],



        [[[[1.],
           [1.],
           [1.]],

          [[1.],
           [1.],
           [1.]]]]])


In [25]:
# les try squeezing and unsqueez
x=torch.arange(1,10)
x_squuezed=torch.squeeze(x)
print(f"the squeezed version: {x_squuezed.shape}")
print(f"the value is: {x_squuezed}")

unsquuezed=x_squuezed.unsqueeze(dim=0)
print(f"the unsquuezed version is: {unsquuezed.shape}")
print(f"the value of the tensor is : {unsquuezed}")

the squeezed version: torch.Size([9])
the value is: tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])
the unsquuezed version is: torch.Size([1, 9])
the value of the tensor is : tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]])


In [26]:
# les try squeezing and unsqueez
x=torch.arange(1,10)
x_squuezed=torch.squeeze(x)
print(f"the squeezed version: {x_squuezed.shape}")
print(f"the value is: {x_squuezed}")

unsquuezed=x_squuezed.unsqueeze(dim=1)
print(f"the unsquuezed version is: {unsquuezed.shape}")
print(f"the value of the tensor is : {unsquuezed}")

the squeezed version: torch.Size([9])
the value is: tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])
the unsquuezed version is: torch.Size([9, 1])
the value of the tensor is : tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]])


In [28]:
# lets try permute 
x=torch.randn([2,3,5])
print(x.shape)
print(x)

torch.Size([2, 3, 5])
tensor([[[-0.1465,  1.6888, -0.6750, -0.3012, -1.1502],
         [ 0.1578,  0.7707, -0.6597,  0.5846, -1.0115],
         [-0.3862,  0.3090,  0.6563, -2.4137,  1.2033]],

        [[ 0.5042, -0.4523, -0.0235, -0.9231, -0.7589],
         [ 2.0408,  0.9242,  0.9511,  0.3349,  0.3273],
         [-1.7370, -1.0936,  0.6475,  1.2108,  0.9759]]])


In [29]:
x_permute=torch.permute(x,(2,0,1))
print(x_permute.shape)
print(x_permute)

torch.Size([5, 2, 3])
tensor([[[-0.1465,  0.1578, -0.3862],
         [ 0.5042,  2.0408, -1.7370]],

        [[ 1.6888,  0.7707,  0.3090],
         [-0.4523,  0.9242, -1.0936]],

        [[-0.6750, -0.6597,  0.6563],
         [-0.0235,  0.9511,  0.6475]],

        [[-0.3012,  0.5846, -2.4137],
         [-0.9231,  0.3349,  1.2108]],

        [[-1.1502, -1.0115,  1.2033],
         [-0.7589,  0.3273,  0.9759]]])


In [ ]:
x=ran