In [1]:
import torch

### Q1.make a 7X7 matrix

In [4]:
tensor=torch.randn([7,7])
print(tensor.shape)
print(tensor)

torch.Size([7, 7])
tensor([[ 1.3378,  0.7216,  2.1969, -1.8932, -0.3889,  0.2093,  0.1286],
        [ 0.5444,  0.1636,  1.3845, -0.1582,  0.8067,  0.0701, -2.1767],
        [-1.9079,  1.7468,  1.3872, -1.1423, -1.3889,  0.8640, -0.6107],
        [-0.4028, -1.1817,  0.0874,  0.2474, -0.2511, -0.5806, -0.4844],
        [ 1.4070, -0.1391,  0.4216,  0.5022,  0.0903,  0.3593, -0.7924],
        [ 1.6196,  1.2641,  0.2234, -0.8360,  1.3384, -0.1696,  0.4585],
        [-1.1315,  1.1193,  0.1812,  0.5961,  0.1446, -0.2704,  0.2048]])


### Q2. multiplication of tensors

In [7]:
tensor2=torch.randn([1,7])
tensor2_reshaped=tensor2.view([7,1])
result=tensor2*tensor2_reshaped

print(f"tensor shape is: {tensor2.shape} ")
print(f"tensor2 after reshaping it {tensor2_reshaped.shape} ")
print(f"result is {result.shape}")
print(result)

tensor shape is: torch.Size([1, 7]) 
tensor2 after reshaping it torch.Size([7, 1]) 
result is torch.Size([7, 7])
tensor([[ 2.1543, -1.7927, -1.3285, -1.9757, -1.5831,  0.2326, -0.1963],
        [-1.7927,  1.4917,  1.1055,  1.6441,  1.3174, -0.1935,  0.1633],
        [-1.3285,  1.1055,  0.8193,  1.2184,  0.9763, -0.1434,  0.1210],
        [-1.9757,  1.6441,  1.2184,  1.8120,  1.4519, -0.2133,  0.1800],
        [-1.5831,  1.3174,  0.9763,  1.4519,  1.1634, -0.1709,  0.1442],
        [ 0.2326, -0.1935, -0.1434, -0.2133, -0.1709,  0.0251, -0.0212],
        [-0.1963,  0.1633,  0.1210,  0.1800,  0.1442, -0.0212,  0.0179]])


In [11]:
torch.manual_seed(0)

tensor=torch.randn([7,7])
print(tensor.shape)
print(tensor)

tensor2=torch.randn([1,7])
tensor2_reshaped=tensor2.view([7,1])
result=tensor2*tensor2_reshaped

print(f"tensor shape is: {tensor2.shape} ")
print(f"tensor2 after reshaping it {tensor2_reshaped.shape} ")
print(f"result is {result.shape}")
print(result)

torch.Size([7, 7])
tensor([[-1.1258, -1.1524, -0.2506, -0.4339,  0.8487,  0.6920, -0.3160],
        [-2.1152,  0.3223, -1.2633,  0.3500,  0.3081,  0.1198,  1.2377],
        [ 1.1168, -0.2473, -1.3527, -1.6959,  0.5667,  0.7935,  0.5988],
        [-1.5551, -0.3414,  1.8530,  0.7502, -0.5855, -0.1734,  0.1835],
        [ 1.3894,  1.5863,  0.9463, -0.8437, -0.6136,  0.8728,  1.0554],
        [ 0.1778, -0.2303, -0.3918,  0.5433, -0.3952,  0.2055,  0.7440],
        [ 1.5210,  3.4105, -1.5312, -1.2341,  1.8197, -0.5515, -1.3253]])
tensor shape is: torch.Size([1, 7]) 
tensor2 after reshaping it torch.Size([7, 1]) 
result is torch.Size([7, 7])
tensor([[ 5.2247e+00, -1.5990e-01, -1.5254e+00,  2.3780e+00,  1.1016e+00,
         -2.5813e+00,  2.6571e+00],
        [-1.5990e-01,  4.8934e-03,  4.6684e-02, -7.2774e-02, -3.3714e-02,
          7.8998e-02, -8.1316e-02],
        [-1.5254e+00,  4.6684e-02,  4.4537e-01, -6.9428e-01, -3.2163e-01,
          7.5365e-01, -7.7577e-01],
        [ 2.3780e+00, -7.2

# seting the seed for the GPU's

In [13]:
torch.cuda.seed()

In [16]:
#finding the maximum value
torch.max(result)

tensor(5.2247)

In [17]:
#finding the minimum value
torch.min(result)

tensor(-2.5813)

In [19]:
big_tensor=torch.randn(1,1,1,10)
print(big_tensor.permute(3,1,2,0))
print(big_tensor.shape)

tensor([[[[-1.3186]]],


        [[[-1.0661]]],


        [[[-2.9771]]],


        [[[ 1.9956]]],


        [[[-0.9683]]],


        [[[-0.7803]]],


        [[[-0.5713]]],


        [[[-0.9645]]],


        [[[-1.0204]]],


        [[[ 1.0309]]]])
torch.Size([1, 1, 1, 10])
