# creating a range using torch

In [1]:
import torch

In [6]:
torch.range(1,10)

C:\Users\nebiy\AppData\Local\Temp\ipykernel_12428\1136815087.py:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(1,10)


tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [7]:
torch.arange(1,10)

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
torch.__version__

'2.1.2'

In [11]:
# creating zeros like
temp=torch.arange(1,25,5)
zeros_like=torch.zeros_like(temp)

In [12]:
print(temp)

tensor([ 1,  6, 11, 16, 21])


In [13]:
print(zeros_like)

tensor([0, 0, 0, 0, 0])


In [14]:
#creating ones like
temp_2=torch.ones_like(temp)

In [15]:
print(temp_2)

tensor([1, 1, 1, 1, 1])


In [21]:
float_32=torch.tensor([2,23,32,14,1])
float_32.dtype

torch.int64

In [26]:
float_64=torch.tensor([2,4,5,2,2],dtype=torch.float64)
float_64.dtype

torch.float64

In [27]:
float_64*float_32

tensor([  4.,  92., 160.,  28.,   2.], dtype=torch.float64)

In [28]:
float_64.dtype

torch.float64

In [30]:
torch.tensor([23,54])

tensor([23, 54])