In [2]:
import torch

# manipulating tensors

## addition

In [3]:
# creating a tensor
tensor=torch.tensor([1,2,3])
tensor+30

tensor([31, 32, 33])

In [4]:
tensor+ torch.tensor([12,12,12])

tensor([13, 14, 15])

## subtraction

In [5]:
tensor - 90

tensor([-89, -88, -87])

### trying out inbuilt functions

In [6]:
torch.mul(tensor,9)

tensor([ 9, 18, 27])

# division 

In [7]:
torch.div(tensor,9)

tensor([0.1111, 0.2222, 0.3333])

# multiplication

### element wise multiplication

In [9]:
tensor * tensor

tensor([1, 4, 9])

In [10]:
tensor

tensor([1, 2, 3])

### matrix-multiplication

In [11]:
torch.matmul(tensor,tensor)

tensor(14)

In [13]:
%%time
# lets compare between the 2
value=0
for i in range(len(tensor)):
    value+=tensor[i]*tensor[i]
print(value)

tensor(14)
CPU times: total: 0 ns
Wall time: 985 µs


In [16]:
%%time
value=torch.matmul(tensor,tensor)
print(value)

tensor(14)
CPU times: total: 0 ns
Wall time: 3.01 ms


In [18]:
# make sure to alwasys have a nice/matching shape matrix
torch.matmul(torch.rand(3,2),torch.rand(2,3))

tensor([[0.3157, 0.4360, 0.0798],
        [0.4032, 0.5671, 0.0994],
        [0.4284, 0.4689, 0.1381]])

# handling shape error on matrix multipliation

In [20]:
tensor_a=torch.tensor([[2,3],
                      [4,5],
                      [6,7]])

tensor_b=torch.ones_like(tensor_a)
torch.mm(tensor_a,tensor_b.T)

tensor([[ 5,  5,  5],
        [ 9,  9,  9],
        [13, 13, 13]])