In [1]:
import torch

# Nature of permuation
* the permuted is the view if the original data

In [3]:
a=torch.randn([2,3,4])
print(a.shape)
print(a)

torch.Size([2, 3, 4])
tensor([[[ 0.6004, -0.8418, -1.3295, -1.4616],
         [-1.7452, -0.9031, -0.5208,  1.0607],
         [ 0.4740, -1.1623,  0.7694,  0.9799]],

        [[ 0.7839, -0.2268,  1.8427, -0.3843],
         [-0.1285,  0.8184,  0.3205, -0.8793],
         [-0.4108,  0.4332,  0.2452,  0.8100]]])


In [4]:
a_perm=a.permute([2,0,1])
print(a_perm.shape)
print(a_perm)

torch.Size([4, 2, 3])
tensor([[[ 0.6004, -1.7452,  0.4740],
         [ 0.7839, -0.1285, -0.4108]],

        [[-0.8418, -0.9031, -1.1623],
         [-0.2268,  0.8184,  0.4332]],

        [[-1.3295, -0.5208,  0.7694],
         [ 1.8427,  0.3205,  0.2452]],

        [[-1.4616,  1.0607,  0.9799],
         [-0.3843, -0.8793,  0.8100]]])


In [7]:
a[0,0,0]=90
print(a)

tensor([[[90.0000, -0.8418, -1.3295, -1.4616],
         [-1.7452, -0.9031, -0.5208,  1.0607],
         [ 0.4740, -1.1623,  0.7694,  0.9799]],

        [[ 0.7839, -0.2268,  1.8427, -0.3843],
         [-0.1285,  0.8184,  0.3205, -0.8793],
         [-0.4108,  0.4332,  0.2452,  0.8100]]])


In [8]:
print(a_perm)

tensor([[[90.0000, -1.7452,  0.4740],
         [ 0.7839, -0.1285, -0.4108]],

        [[-0.8418, -0.9031, -1.1623],
         [-0.2268,  0.8184,  0.4332]],

        [[-1.3295, -0.5208,  0.7694],
         [ 1.8427,  0.3205,  0.2452]],

        [[-1.4616,  1.0607,  0.9799],
         [-0.3843, -0.8793,  0.8100]]])


# indexing value or accesing value on a matrix

In [11]:
x=torch.arange(1,10).reshape([1,3,3])
print(x)

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])


In [12]:
#accesing the first dim
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [13]:
#accessign the second dimension
x[0][0]

tensor([1, 2, 3])

In [14]:
#accessing the last dimension
x[0][0][0]

tensor(1)

In [15]:
x[0,0,0]

tensor(1)

In [17]:
x[0][2][2]

tensor(9)

In [18]:
x[0,2,2]

tensor(9)

In [19]:
#accessing all the target dimesion
x[0,:,1]

tensor([2, 5, 8])

In [20]:
x[0,1,:]

tensor([4, 5, 6])

In [22]:
x[:,0]

tensor([[1, 2, 3]])

In [24]:
x[0,2,2]

tensor(9)

In [25]:
x[:,:,2]

tensor([[3, 6, 9]])