# numpy and tensors:
* turnig ndarray(numpy) into tensor
* and turing tensor into numpy

In [3]:
import numpy as np
import torch

In [9]:
#changing from numpy into tensor
np_array=np.arange(1,10)
tensor=torch.from_numpy(np_array).type(torch.float32)
print(np_array)
print(tensor)

[1 2 3 4 5 6 7 8 9]
tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])


In [12]:
tensor.dtype

torch.float32

In [15]:
np_array.dtype

dtype('int32')

In [10]:
torch.arange(1,9).dtype

torch.int64

In [14]:
#changing from tensor into numpy
tensor=torch.ones(8)
numpy_tensor=tensor.numpy()
tensor,numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1., 1.], dtype=float32))